const cases=[
{id:'homeless',name:'Бомжик',price:0.2,icon:'assets/cases/homeless.png',rewards:[['0.1 TON','assets/rewards/ton-01.png','TON',50],['0.2 TON','assets/rewards/ton-02.png','TON',35],['NFT «Lol Pop»','assets/nft/lol-pop.png','NFT',7],['NFT «B-Day»','assets/nft/b-day.png','NFT',5],['NFT «Spring Basket»','assets/nft/spring-basket.png','NFT',3]]},
{id:'starter',name:'Стартер',price:0.5,icon:'assets/cases/starter.png',rewards:[['0.2 TON','assets/rewards/ton-02.png','TON',45],['0.5 TON','assets/rewards/ton-05.png','TON',35],['NFT «Candy Cane»','assets/nft/candy-cane.png','NFT',12],['NFT «Fortune Cookie»','assets/nft/fortune-cookie.png','NFT',6],['NFT «Winter Mitten»','assets/nft/winter-mitten.png','NFT',2]]},
{id:'student',name:'Студент',price:1,icon:'assets/cases/student.png',rewards:[['0.4 TON','assets/rewards/ton-04.png','TON',40],['1 TON','assets/rewards/ton-10.png','TON',35],['1.5 TON','assets/rewards/ton-15.png','TON',12],['NFT «Party Popper»','assets/nft/party-popper.png','NFT',8],['NFT «Gingerbread Man»','assets/nft/gingerbread-man.png','NFT',5]]},
{id:'lucky',name:'Фартовый',price:2.5,icon:'assets/cases/lucky.png',rewards:[['1 TON','assets/rewards/ton-10.png','TON',42],['2.5 TON','assets/rewards/ton-25.png','TON',30],['4 TON','assets/rewards/ton-40.png','TON',15],['NFT «Spiced Wine»','assets/nft/spiced-wine.png','NFT',8],['NFT «Teddy Bear»','assets/nft/teddy-bear.png','NFT',5]]},
{id:'winter',name:'Зимний',price:5,icon:'assets/cases/winter.png',rewards:[['2 TON','assets/rewards/ton-20.png','TON',40],['5 TON','assets/rewards/ton-50.png','TON',32],['8 TON','assets/rewards/ton-80.png','TON',14],['NFT «Santa Hat»','assets/nft/santa-hat.png','NFT',10],['NFT «Snow Globe»','assets/nft/snow-globe.png','NFT',4]]},
{id:'mystic',name:'Мистик',price:10,icon:'assets/cases/mystic.png',rewards:[['4 TON','assets/rewards/ton-40.png','TON',38],['10 TON','assets/rewards/ton-100.png','TON',30],['15 TON','assets/rewards/ton-150.png','TON',18],['NFT «Spooky Pumpkin»','assets/nft/spooky-pumpkin.png','NFT',9],['NFT «Magic Potion»','assets/nft/magic-potion.png','NFT',5]]},
{id:'gentleman',name:'Джентльмен',price:20,icon:'assets/cases/gentleman.png',rewards:[['8 TON','assets/rewards/ton-80.png','TON',35],['20 TON','assets/rewards/ton-200.png','TON',32],['30 TON','assets/rewards/ton-300.png','TON',18],['NFT «Top Hat»','assets/nft/top-hat.png','NFT',10],['NFT «Vintage Cigar»','assets/nft/vintage-cigar.png','NFT',5]]},
{id:'star',name:'Звездный',price:35,icon:'assets/cases/star.png',rewards:[['15 TON','assets/rewards/ton-150.png','TON',40],['35 TON','assets/rewards/ton-350.png','TON',30],['50 TON','assets/rewards/ton-500.png','TON',16],['NFT «Green Star»','assets/nft/green-star.png','NFT',9],['NFT «Blue Star»','assets/nft/blue-star.png','NFT',5]]},
{id:'major',name:'Мажор',price:60,icon:'assets/cases/major.png',rewards:[['25 TON','assets/rewards/ton-250.png','TON',38],['60 TON','assets/rewards/ton-600.png','TON',30],['90 TON','assets/rewards/ton-900.png','TON',18],['NFT «Golden Ring»','assets/nft/golden-ring.png','NFT',9],['NFT «Christmas Tree»','assets/nft/christmas-tree.png','NFT',5]]},
{id:'sheikh',name:'Шейх',price:120,icon:'assets/cases/sheikh.png',rewards:[['50 TON','assets/rewards/ton-500.png','TON',40],['120 TON','assets/rewards/ton-1200.png','TON',30],['180 TON','assets/rewards/ton-1800.png','TON',17],['NFT «Golden Dragon»','assets/nft/golden-dragon.png','NFT',9],['NFT «Diamond Ring»','assets/nft/diamond-ring.png','NFT',4]]}
];
const $=id=>document.getElementById(id);let selected=null,spinning=false;
function scrollToCases(){$('casesSection').scrollIntoView({behavior:'smooth'})}
function renderCases(){const g=$('casesGrid');g.innerHTML=cases.map(c=>`<article class="case-card"><div class="case-image"><img src="${c.icon}" alt="${c.name}"></div><div class="case-name">${c.name}</div><div class="case-price">${c.price} TON</div><button onclick="openCase('${c.id}')">ОТКРЫТЬ</button></article>`).join('')}
function openCase(id){selected=cases.find(c=>c.id===id);$('casesSection').classList.add('hidden');$('caseSection').classList.remove('hidden');$('caseName').textContent=selected.name;$('casePrice').textContent=`${selected.price} TON`;$('caseIcon').src=selected.icon;$('result').classList.add('hidden');$('openingStatus').textContent='ГОТОВО';$('openingHint').textContent='Вращаем весь каталог наград…';renderProbabilities();buildReel(selected.rewards);window.scrollTo({top:0,behavior:'smooth'})}
$('backButton').onclick=()=>{$('caseSection').classList.add('hidden');$('casesSection').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};
function renderProbabilities(){const g=$('rewardsGrid');g.innerHTML=selected.rewards.map(r=>`<div class="prob"><img src="${r[1]}" alt=""><div><div class="name">${r[0]}</div><div class="kind">${r[2]}</div></div><div class="chance">${r[3]}%</div></div>`).join('')}
function pickWeighted(){let n=Math.random()*100;for(const r of selected.rewards){n-=r[3];if(n<0)return r}return selected.rewards.at(-1)}
function buildReel(rewardList){const reel=$('reel');reel.style.transition='none';reel.style.transform='translateX(0)';const arr=[];for(let i=0;i<50;i++)arr.push(rewardList[i%rewardList.length]);reel.innerHTML=arr.map((r,i)=>`<div class="reel-card" data-i="${i}"><img src="${r[1]}" alt=""><b>${r[0]}</b><small>${r[2]}</small></div>`).join('')}
$('openButton').onclick=()=>{if(!selected||spinning)return;spinning=true;$('openButton').disabled=true;$('openingStatus').textContent='КРУТИМ';$('openingHint').textContent='Каталог вращается — результат уже определён шансами…';$('result').classList.add('hidden');const target=pickWeighted();const idx=36+selected.rewards.indexOf(target);const reel=$('reel');const cardW=155;const container=document.querySelector('.reel-wrap');const center=(container.clientWidth/2)-(cardW/2);const jitter=(Math.random()-.5)*28;const distance=idx*cardW-center+jitter;requestAnimationFrame(()=>{reel.style.transition='transform 4.8s cubic-bezier(.08,.72,.12,1)';reel.style.transform=`translateX(${-distance}px)`});setTimeout(()=>showResult(target),5000)};
function showResult(r){$('openingStatus').textContent='ГОТОВО';$('openingHint').textContent='Результат выбран по таблице вероятностей.';const box=$('result');box.classList.remove('hidden');box.innerHTML=`<div class="win-label">НАГРАДА ВЫПАЛА</div><img src="${r[1]}" alt=""><strong>${r[0]}</strong><small>Шанс этой награды: ${r[3]}% · DEMO</small>`;$('openButton').disabled=false;spinning=false}
renderCases();
